### ISSUE TITLE
Meme in a bottle always crashes on startup in minecraft 1.14.4

### ISSUE THREAD

**Issue by yourizuring** [Mrbysco/MemeInABottle#4]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4-2-20 14:31
Description: Rendering overlay

java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711) ~[?:1.8.0_51] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734) ~[?:1.8.0_51] {}
	at net.minecraft.client.audio.SoundHandler.func_212854_a_(SoundHandler.java:64) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundHandler.func_212854_a_(SoundHandler.java:35) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3428/650332668.get(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$396/456785282.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1238614688 bytes (1181 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.115.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.115.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.115.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.115.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.115.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.115
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.115-client.jar Minecraft {minecraft@1.14.4 ENQUEUE_IMC}
		Lucky-Block-Mod-1.14.4 (1).jar Lucky Block {lucky@7.9.1 ENQUEUE_IMC}
		AnimalNet-Mod-1.14.4.jar AnimalNet {animalnet@v1.14.4 Forge b4 ENQUEUE_IMC}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 ENQUEUE_IMC}
		giantspawn_1.14-1.0.2.jar Giant Spawn {giantspawn@1.0.2 ENQUEUE_IMC}
		Extra-Bows-Mod-1.14.4.jar Extra Bows {extrabows@v1.14.4 b9 ENQUEUE_IMC}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 ENQUEUE_IMC}
		Random-Enchants-Mod-1.14.4.jar Random Enchants {randomenchants@2.2.3 ENQUEUE_IMC}
		More-Ores-In-ONE-Mod-1.14.4.jar More Ores in ONE {moreoresinone@1.5 ENQUEUE_IMC}
		rediscovered-1.14.4-1.1.1.jar Rediscovered {rediscovered@1.1.1 ENQUEUE_IMC}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 ENQUEUE_IMC}
		levelhearts-1.14.4-2.1.0.jar LevelHearts {levelhearts@2.1.0 ENQUEUE_IMC}
		halloween_luckyblock-1.14.4-2.3.0.9.jar Halloween LuckyBlock {halloween_luckyblock@2.3.0.9 ENQUEUE_IMC}
		earthmobsmod-1.14.4-0.1.0.6-Beta.jar Earth Mobs Mod {earthmobsmod@0.1.0.6 ENQUEUE_IMC}
		HMM15MC1.14.4.jar HMM1.14.4 {h_m_m@15 ENQUEUE_IMC}
		PyramidPlunder-1.14.4-1.1.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 ENQUEUE_IMC}
		MemeInABottle-1.14.4-3.0.0.jar Meme in a bottle {memeinabottle@3.0.0 ENQUEUE_IMC}
		DungeonCrawl-1.14.4-1.6.0.jar Dungeon Crawl {dungeoncrawl@1.6.0 ENQUEUE_IMC}
		cg_1.14-1.0.jar Crying Ghasts {cg@1.0 ENQUEUE_IMC}
		u_team_core-1.14.4-2.8.0.140.jar U Team Core {uteamcore@2.8.0.140 ENQUEUE_IMC}
		ChanceCubes-1.14.4-4.0.0.298.jar Chance Cubes {chancecubes@1.14.4-4.0.0.298 ENQUEUE_IMC}
		Forgiving-Void-Mod-1.14.4.jar Forgiving Void {forgivingvoid@3.0.8 ENQUEUE_IMC}
		Bouncing-Balls-Mod-1.14.4.jar Bouncing Balls {bouncing_balls@6.0.1 ENQUEUE_IMC}
		Death-Quotes-Mod-1.14.4.jar DeathQuotes {deathquotes@1.0 ENQUEUE_IMC}
		Exp-Ore-Mod-1.14.4.jar Exp Ore Block Mod {exp_ore@1.4 ENQUEUE_IMC}
		illagers_plus-2.0.jar Illagers+ {illagers_plus@2.0(BETA) ENQUEUE_IMC}
		GemsPlusPlus-Mod-1.14.4.jar GemsPlusPlus {gemsplusplus@V1.4.0 ENQUEUE_IMC}
		Get-In-The-Bucket-Mod-1.14.4.jar Get In The Bucket Mod {getinthebucketmod@1.3.1 ENQUEUE_IMC}
		forge-1.14.4-28.1.115-universal.jar Forge {forge@28.1.115 ENQUEUE_IMC}
		Classic-Bars-Mod-1.14.4.jar Classic Bar {classicbar@2.0.0a ENQUEUE_IMC}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 ENQUEUE_IMC}
	Launched Version: 1.14.4-forge-28.1.115
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 630 GL version 4.4.0 - Build 22.20.16.4708, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by Mrbysco** [comment]
Does it boot up without Meme In A Bottle?

**Comment by yourizuring** [comment]
Yes

Op za 8 feb. 2020 20:12 schreef Mrbysco <notifications@github.com>:

**Comment by Mrbysco** [comment]
Could you try version 3.0.1?
